import { logger } from '@/lib/utils/logger'

const TELEGRAM_API_BASE = 'https://api.telegram.org/bot'

export class TelegramServer {
  private botToken: string | undefined
  private chatId: string | undefined

  constructor() {
    this.botToken = process.env.TELEGRAM_BOT_TOKEN
    this.chatId = process.env.TELEGRAM_CHAT_ID
  }

  async sendMessage(message: string): Promise<Record<string, unknown>> {
    logger.info('telegram', 'TelegramServer.sendMessage', { messageLength: message.length })
    if (!this.botToken || !this.chatId) {
      return { success: false, error: 'Telegram is not configured. Set TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID.' }
    }
    try {
      const response = await fetch(`${TELEGRAM_API_BASE}${this.botToken}/sendMessage`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ chat_id: this.chatId, text: message, parse_mode: 'HTML' }),
      })
      const data = await response.json()
      if (!data.ok) throw new Error(data.description || 'Telegram API error')
      return { success: true, messageId: data.result?.message_id }
    } catch (error) {
      logger.error('telegram', 'Failed to send message', { error: String(error) })
      return { success: false, error: String(error) }
    }
  }

  async sendTodayReport(): Promise<Record<string, unknown>> {
    logger.info('telegram', 'TelegramServer.sendTodayReport')
    const now = new Date()
    const dateStr = now.toLocaleDateString('en-US', {
      weekday: 'long', year: 'numeric', month: 'long', day: 'numeric',
    })
    const memoryUsage = process.memoryUsage()
    const heapUsed = Math.round(memoryUsage.heapUsed / 1024 / 1024)
    const heapTotal = Math.round(memoryUsage.heapTotal / 1024 / 1024)

    let report = `<b>Daily Report - ${dateStr}</b>\n\n`
    report += `<b>System Status:</b>\n`
    report += `\u2022 Platform: ${process.platform}\n`
    report += `\u2022 Uptime: ${Math.floor(process.uptime() / 60)} minutes\n`
    report += `\u2022 Memory: ${heapUsed}MB / ${heapTotal}MB\n`
    report += `\u2022 Node: ${process.version}\n\n`
    report += `<i>Generated by J.A.R.V.I.S AI Control Hub</i>`

    return this.sendMessage(report)
  }
}

export const telegramServer = new TelegramServer()
