import { logger } from '@/lib/utils/logger'

const TELEGRAM_API_BASE = 'https://api.telegram.org/bot'

function getBotToken(): string | undefined {
  return process.env.TELEGRAM_BOT_TOKEN
}

function getChatId(): string | undefined {
  return process.env.TELEGRAM_CHAT_ID
}

export async function sendTelegramMessage(message: string): Promise<{ success: boolean; messageId?: number; error?: string }> {
  const startTime = Date.now()
  logger.info('telegram', 'sendTelegramMessage called', { messageLength: message.length })

  const botToken = getBotToken()
  const chatId = getChatId()

  if (!botToken || !chatId) {
    const error = 'Telegram is not configured. Set TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID environment variables.'
    logger.error('telegram', error)
    return { success: false, error }
  }

  try {
    const url = `${TELEGRAM_API_BASE}${botToken}/sendMessage`
    const response = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        chat_id: chatId,
        text: message,
        parse_mode: 'HTML',
      }),
    })

    const data = await response.json()

    if (!data.ok) {
      throw new Error(data.description || 'Failed to send Telegram message')
    }

    const duration = Date.now() - startTime
    logger.info('telegram', 'Message sent successfully', {
      messageId: data.result?.message_id,
      durationMs: duration,
    })

    return { success: true, messageId: data.result?.message_id }
  } catch (error) {
    logger.error('telegram', 'Failed to send message', { error: String(error) })
    return { success: false, error: String(error) }
  }
}

export async function sendTodayReportToTelegram(): Promise<{ success: boolean; messageId?: number; error?: string }> {
  const startTime = Date.now()
  logger.info('telegram', 'sendTodayReportToTelegram called')

  const now = new Date()
  const dateStr = now.toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })

  let report = `📋 <b>Daily Report - ${dateStr}</b>\n\n`

  const memoryUsage = process.memoryUsage()
  const heapUsed = Math.round(memoryUsage.heapUsed / 1024 / 1024)
  const heapTotal = Math.round(memoryUsage.heapTotal / 1024 / 1024)

  report += `<b>System Status:</b>\n`
  report += `• Platform: ${process.platform}\n`
  report += `• Uptime: ${Math.floor(process.uptime() / 60)} minutes\n`
  report += `• Memory: ${heapUsed}MB / ${heapTotal}MB\n`
  report += `• Node: ${process.version}\n\n`
  report += `<i>Report generated by XENA AI Control Hub</i>`

  return sendTelegramMessage(report)
}
